# Generated by Django 3.2.3 on 2021-05-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('AlumnoId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Apellido', models.CharField(max_length=100)),
                ('Correo', models.CharField(max_length=100)),
                ('Grupo', models.CharField(max_length=100)),
                ('Materia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Califica',
            fields=[
                ('CalificaId', models.AutoField(primary_key=True, serialize=False)),
                ('Alumno', models.CharField(max_length=100)),
                ('Tarea', models.CharField(max_length=100)),
                ('Grupo', models.CharField(max_length=100)),
                ('CalificaNum', models.CharField(max_length=100)),
                ('Retro', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('GrupoId', models.AutoField(primary_key=True, serialize=False)),
                ('Grupo', models.CharField(max_length=100)),
                ('Materia', models.CharField(max_length=100)),
                ('Hora', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('TareaId', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Materia', models.CharField(max_length=100)),
                ('Grupo', models.CharField(max_length=100)),
                ('Descrip', models.CharField(max_length=100)),
                ('Fecha', models.DateField()),
                ('Archivo', models.CharField(max_length=100)),
            ],
        ),
    ]
